site_name: DropDog - Drupal 8.x distribution
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

pages:
- Home: 'index.md'
- General:
    - General: 'general.md'
- Development:
    - Parameters: 'parameters.md'
    - Infrastructure: 'infrastructure.md'
    - Development: 'development.md'
    - Theming: 'theming.md'
    - Tests: 'tests.md'
    - Development thoughts: 'thoughts.md'
- Reviews:
    - 'Entity Review': 'review/entity.md'
    - 'Views Review': 'review/views.md'
- Scripts: 'scripts.md'
- Learn: 'learn.md'
- Terminology: 'terminology.md'
