site_name: DropDog - Drupal 8.x distribution
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

pages:
- Home: 'index.md'
- General: 'general.md'
- Learn: 'learn.md'
- Parameters: 'parameters.md'
- Infrastructure: 'infrastructure.md'
- Development: 'development.md'
- Theming: 'theming.md'
- Tests: 'tests.md'
- Reviews - Entity: 'review/entity.md'
- Reviews - Views: 'review/views.md'
- Scripts: 'scripts.md'
- Development thoughts: 'thoughts.md'
- Terminology: 'terminology.md'
