site_name: DropDog - Drupal 8.x distribution
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

pages:
- Home: 'index.md'
- General: 'general.md'
- Learn: 'learn.md'
- Parameters: 'parameters.md'
- Infrastructure: 'infrastructure.md'
- Development: 'development.md'
- Theming: 'theming.md'
- Scripts: 'scripts.md'
- Terminology: 'terminology.md'
