site_name: DropDog - Drupal 8.x distribution
markdown_extensions:
    - smarty
    - toc:
        permalink: True
    - sane_lists

pages:
- Home: 'index'
- General: 'general'
- Learn: 'learn'
- Parameters: 'parameters'
- Infrastructure: 'infrastructure'
- Development: 'development'
- Theming: 'theming'
- Scripts: 'scripts'
- Terminology: 'terminology'
